// src/components/common/ShowMore.tsx
// src/components/show-more-less/show-more-less.tsx
import { $, component$, Slot, useSignal, useStyles$, useVisibleTask$ } from "@builder.io/qwik";


interface ShowMoreLessProps {
    startingHeightClass: string;      // Maximum height before content is truncated
    buttonLabels?: {        // Optional custom button labels
        more: string;
        less: string;
    };
}

export const ShowMore = component$((props: ShowMoreLessProps) => {
    // Default props
    const {
        startingHeightClass,
        buttonLabels = {more: 'Show more', less: 'Show less'},
    } = props;

    // State signals
    const contentRef = useSignal<HTMLDivElement>();
    const contentHeight = useSignal<number>(0);
    const isExpanded = useSignal<boolean>(false);
    const showToggle = useSignal<boolean>(false);

    // Toggle expanded state
    const toggleExpand$ = $(() => {
        isExpanded.value = !isExpanded.value;
    });

    // Measure content height on component mount and window resize
    useVisibleTask$(({track}) => {
        // Re-run when contentRef changes
        track(() => contentRef.value);

        if (contentRef.value) {
            // Get the actual content height
            const height = contentRef.value.scrollHeight;
            contentHeight.value = height;

            // Only show toggle if content height exceeds max height
            // showToggle.value = height > maxHeight;
        }
    });

    // overflow: hidden;
    // text-overflow: ellipsis;
    // white-space: nowrap;
    return (
        <div>
            <div class={`relative inline-flex overflow-hidden text-ellipsis ${isExpanded.value ? "max-h-full" : startingHeightClass}`}>
                <Slot />
            </div>
            <p class="underline cursor-pointer"
                onClick$={toggleExpand$}
            >
                {isExpanded.value ? buttonLabels.less : buttonLabels.more}
            </p>
        </div>
    );});

// src/components/interactive/ShowMore.svelte
<script>
    import { onMount } from 'svelte';

    // Props interface
    let {
        startingHeightClass,
        buttonLabels = { more: 'Show more', less: 'Show less' }
    } = $props();

    // State using Svelte 5 runes
    let contentRef = $state();
    let contentHeight = $state(0);
    let isExpanded = $state(false);
    let showToggle = $state(false);

    // Toggle expanded state
    function toggleExpand() {
        isExpanded = !isExpanded;
    }

    onMount(() => {
        if (contentRef) {
            // Get the actual content height
            const height = contentRef.scrollHeight;
            contentHeight = height;
        }
    });
</script>

<div bind:this={contentRef}
    class="relative text-base inline-flex overflow-hidden text-ellipsis {isExpanded ? 'max-h-full' : startingHeightClass}"
>
    <slot />
</div>
<p class="underline text-base cursor-pointer my-4" onclick={toggleExpand} >
    {isExpanded ? buttonLabels.less : buttonLabels.more}
</p>
