// src/components/interactive/CookieConsent/CookieConsent.tsx
import { $, component$, type QRL, useStore, useStylesScoped$, useVisibleTask$ } from '@builder.io/qwik';
import styles from './cookie-consent.css?inline';
import {
    deleteAllCookiesExceptConsent,
    deleteCookie,
    disableGa,
    enableGa,
    getCookie,
    setCookie
} from "@utils/browser.ts";
import { ShowMore } from "@components/common/ShowMore";
import { CookiesAccordion } from "./CookiesAccordion";

const BUTTON_CLASSES = "rounded-md bg-slate-800 py-2 px-4 m-1 border border-transparent text-center text-sm text-white transition-all shadow-md hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none";

interface ButtonsProps {
    onPreference$: QRL<() => void>;
    onReject$: QRL<() => void>;
    onAccept$: QRL<() => void>;
}

const CookieButtons = component$<ButtonsProps>(({ onPreference$, onReject$, onAccept$ }) => {
    return (
        <div class={`cookie-buttons`}>
            <button
                id="cookie-preference-btn"
                onClick$={onPreference$}
                class={BUTTON_CLASSES}
                type="button"
            >
                Preference
            </button>
            <button
                id="cookie-reject-btn"
                onClick$={onReject$}
                class={BUTTON_CLASSES}
                type="button"
            >
                Reject Non-Essential
            </button>
            <button
                id="cookie-accept-btn"
                onClick$={onAccept$}
                class={BUTTON_CLASSES}
                type="button"
            >
                Accept All
            </button>
        </div>
    );
});

export const CookieConsent = component$(() => {
    useStylesScoped$(styles);
    const state = useStore({isVisible: false, isPreferenceActive: true, currentPath: "" });

    // Equivalent to useEffect in React
    useVisibleTask$(() => {
        const cookie = getCookie('cookie-consent');
        state.isVisible = !cookie;
        if (cookie === 'accepted') enableGa();
    }, { strategy: "document-ready" });

    const handlePreference$ = $(() => {
        state.isPreferenceActive = !state.isPreferenceActive;
    });

    const handleAccept$ = $(() => {
        setCookie('cookie-consent', 'accepted', 365);
        setCookie('analytics-cookies', 'accepted', 365);
        state.isVisible = false;
        enableGa();
    });

    const handleReject$ = $(() => {
        setCookie('cookie-consent', 'rejected', 365);
        setCookie('analytics-cookies', 'rejected', 365);
        state.isVisible = false;
        deleteAllCookiesExceptConsent();
        disableGa();
    });

    return (
        <div class={[
            state.isPreferenceActive ? "" : "overflow-hidden",
            state.isVisible ? "" : "hidden",
        ]}>
            <div class={["cookie-normal cookie-banner rounded-full",
                state.isPreferenceActive ? "cookie-normal-pref-active" : ""
            ]}>
                <svg class="cookie w-16 h-16 absolute -top-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path fill="#dda85f" d="m36.9 22.7l2.5-18.6C37 3.5 34.6 2 32 2s-5 1.5-7.5 2.2c-2.5.6-5.3.5-7.5 1.8s-3.6 3.8-5.4 5.6S7.3 14.8 6 17s-1.2 5-1.9 7.5C3.5 27 2 29.4 2 32s1.5 5 2.2 7.5c.6 2.5.5 5.3 1.8 7.5s3.8 3.6 5.6 5.4s3.1 4.3 5.4 5.6c2.2 1.3 5 1.2 7.5 1.9c2.5.6 4.9 2.1 7.5 2.1s5-1.5 7.5-2.2s5.3-.6 7.5-1.9s3.6-3.8 5.4-5.6s4.3-3.1 5.6-5.4c1.3-2.2 1.2-5 1.9-7.5c.6-2.4 2.1-4.8 2.1-7.4s-2.1-8.1-2.1-8.1z"/><path fill="#f2cb7d" d="M59.4 22.4c-1 .3-2.4.2-3.9-.4c-2.1-.8-3.4-2.5-3.8-4.5c-1 .3-3.4 0-5-1c-2.4-1.5-2.9-5.7-2.9-5.7c-2.7-.8-4.7-4-4.4-6.7c-2.2-.6-5-.5-7.4-.5s-4.6 1.4-6.8 2c-2.3.6-4.9.5-6.9 1.7s-3.3 3.5-4.9 5.1c-1.7 1.7-4 2.9-5.1 4.9c-1.2 2-1.1 4.6-1.7 6.9c-.6 2.2-2 4.4-2 6.8s1.4 4.6 2 6.8c.6 2.3.5 4.9 1.7 6.9s3.5 3.3 5.1 4.9c1.7 1.7 2.9 4 4.9 5.1c2 1.2 4.6 1.1 6.9 1.7c2.2.6 4.4 2 6.8 2s4.6-1.4 6.8-2c2.3-.6 4.9-.5 6.9-1.7s3.3-3.5 4.9-5.1c1.7-1.7 4-2.9 5.1-4.9c1.2-2 1.1-4.6 1.7-6.9c.6-2.2 3-4 3.3-6.4c.8-3.9-1.2-8.3-1.3-9"/><path fill="#dda85f" d="m50.1 10.8l-1.4 1.4l-1.3-1.4l1.3-1.3zm5.7 7l-.6.7l-.7-.7l.7-.7zm-5-4.6l-.7.7l-.7-.7l.7-.7zm-6.2-6.1l-.7.7l-.7-.7l.7-.7zm12.6 13.2l-.7.7l-.7-.7l.7-.7zm.6-2.5l-.7.7l-.7-.7l.7-.7z"/><path fill="#6d4934" d="M11.8 20.6c-1 1.7.5 4.8 2.5 5.7c2.9 1.2 4.6 1.4 6.4-1.7c.6-1.1 1.4-4 1.1-4.7c-.4-1-2.1-3-3.2-3c-3.1.1-6.1 2.5-6.8 3.7"/><path fill="#a37f6a" d="M12.3 20.6c-.7 1.2 1.1 4.8 3.5 4.5c3.3-.4 3-7.2 1.6-7.2c-2.4 0-4.6 1.8-5.1 2.7"/><path fill="#6d4934" d="M45.2 39.1c1.4-.4 2.4-2.9 1.8-4.4c-.9-2.3-1.8-3.3-4.4-2.6c-.9.3-3 1.4-3.2 1.9c-.3.8-.5 2.8.1 3.4c1.7 1.7 4.7 2 5.7 1.7"/><path fill="#a37f6a" d="M43.8 36.7c1.1-.3 2.8-3.7 1-3.9c-3.1-.5-5.5 1-5.2 2.7s3.4 1.4 4.2 1.2"/><path fill="#6d4934" d="M24.9 44.5c-.3-1.2-2.5-2.1-3.9-1.5c-2 .8-2.9 1.5-2.2 3.8c.2.8 1.2 2.6 1.7 2.7c.7.3 2.4.4 2.9-.1c1.5-1.4 1.7-4 1.5-4.9"/><path fill="#a37f6a" d="M23.2 43.6c-.2-.9-4.4.4-4 2c.8 2.7.8 3.1 1.6 3c1.5-.4 2.5-4.3 2.4-5"/><path fill="#6d4934" d="M51.1 25.5c-1.2.3-2.1 2.5-1.5 3.9c.8 2 2.7 2.3 4.8 1.2c1.8-.9 1.9-4.1 1.4-4.7c-1.5-1.5-3.8-.6-4.7-.4"/><path fill="#a37f6a" d="M50.6 26.6c-.6.7-1.1 3.5.4 3.1c2.7-.8 4.6-3.5 3.4-3.9c-1.5-.5-3.1 0-3.8.8"/><path fill="#6d4934" d="m22.74 16.112l1.98-1.98l1.98 1.98l-1.98 1.98z"/><path fill="#dda85f" d="m14.706 33.483l1.979-1.98l1.98 1.979l-1.979 1.98zm19.992 11.328l1.98-1.98l1.98 1.98l-1.98 1.98zm-2.66-5.522l2.687-2.687l2.687 2.687l-2.687 2.687zM24.696 9.827l2.687-2.687l2.687 2.687l-2.687 2.687z"/><path fill="#6d4934" d="m41.122 46.347l1.98-1.98l1.98 1.98l-1.98 1.98zm7.954-11.132l1.98-1.98l1.98 1.98l-1.98 1.98zm-7.264-10.578l.99-.99l.99.99l-.99.99zM13.726 38.266l.99-.99l.99.99l-.99.99z"/></svg>
                <div class="cookie-content p-4 justify-around items-center gap-4">
                    <p class="text-center mx-12">
                        This website uses cookies to ensure you get the best experience.<br/>
                        Of course they are turned off by default. <a class="underline" href="/privacy-policy">Learn
                        more</a>
                    </p>
                    <CookieButtons onPreference$={handlePreference$} onReject$={handleReject$} onAccept$={handleAccept$} />
                </div>
            </div>
            <div class={[
                "cookie-banner cookie-pref",
                state.isPreferenceActive ? "cookie-pref-active" : ""
            ]}>
                <div class="cookie-pref-content">
                    <Preferences />
                </div>
                <CookieButtons onPreference$={handlePreference$} onReject$={handleReject$} onAccept$={handleAccept$} />
            </div>
        </div>
    );
});

const Preferences = component$(() => {
    return (
        <>
            <h3>Cookies Preferences</h3>
            <ShowMore startingHeightClass="max-h-28">
                <p class="mt-6">
                    We use cookies to enhance your website experience. These digital tools help with
                    navigation and enable important features.
                    "Necessary" cookies are automatically saved to your browser as they're essential for the
                    site to function properly.
                    <br/>
                    <br/>
                    Additionally, we employ third-party cookies to analyze your usage patterns, remember
                    your preferences, and deliver relevant content and ads. These cookies will only be
                    stored if you give permission.
                    <br/>
                    <br/>
                    You have full control to enable or disable any cookies, though turning off certain ones
                    might impact how you experience our website.
                </p>
            </ShowMore>
            <CookiesAccordion />
        </>
    );
});

// src/components/interactive/CookieConsent/CookieConsent.svelte
<script lang="ts">
    import CookieIcon from '@assets/icons/cookie.svg?raw';
    import CloseIcon from '@assets/icons/close.svg?raw';
    import Buttons from './Buttons.svelte';
    import { slide } from 'svelte/transition';
    import Preferences from "@components/interactive/CookieConsent/Preferences.svelte";
    import {deleteAllCookiesExceptConsent, disableGa, enableGa, setCookie} from "@utils/browser";

    // Reactive state using Svelte 5 runes
    let state = $state({
        isPreferenceActive: true,
        isVisible: true
    });

    // Event handlers
    function handlePreference() {
        state.isPreferenceActive = !state.isPreferenceActive;
    }

    function handleReject() {
        setCookie('cookie-consent', 'rejected', 365);
        setCookie('analytics-cookies', 'rejected', 365);
        state.isVisible = false;
        deleteAllCookiesExceptConsent();
        disableGa();
    }

    function handleAccept() {
        setCookie('cookie-consent', 'accepted', 365);
        setCookie('analytics-cookies', 'accepted', 365);
        state.isVisible = false;
        enableGa();
    }
</script>

<div class={[
  state.isPreferenceActive ? "" : "overflow-hidden",
  state.isVisible ? "" : "hidden"
].join(" ")}>
    <div class={[
    "cookie-normal cookie-banner rounded-full",
    state.isPreferenceActive ? "cookie-normal-pref-active" : ""
  ].join(" ")}>
        <span class="cookie w-16 h-16 absolute -top-5">
            {@html CookieIcon}
        </span>
        <div class="cookie-content p-4 justify-around items-center gap-4">
            <p class="text-center mx-12">
                This website uses cookies to ensure you get the best experience.<br/>
                Of course they are turned off by default. <a class="underline" href="/privacy-policy">Learn more</a>
            </p>
            <Buttons
                onPreference={handlePreference}
                onReject={handleReject}
                onAccept={handleAccept}
            />
        </div>
    </div>

    {#if state.isPreferenceActive}
        <div transition:slide class="cookie-banner cookie-pref">
            <div class="flex justify-between items-center mb-4">
                <h3>Cookies Preferences</h3>
                <button type="button" onclick={handlePreference}>
                    {@html CloseIcon }
                </button>
            </div>
            <div class="cookie-pref-content">
                <Preferences />
            </div>
            <Buttons
                    onPreference={handlePreference}
                    onReject={handleReject}
                    onAccept={handleAccept}
            />
        </div>
    {/if}
</div>

<style>
    @import './cookie-consent.css';
</style>
